### ISSUE TITLE
Improving design

### ISSUE THREAD

**Issue by jlerbsc** [quick-perf/quickperf#100]
I analyzed the source code of the quickperf sql subproject with my own 3d analyzer tool.

http://jperf.com/qperf/

Probably it can help you to improve your project, you can navigate into classes/interfaces or packages and see all the relationships between all the components (visibility option) or analyse the complexity from various aspects (dependencies between classes, responsability, or lines of code), or analyze design problems (coupling, cyclic dependencies).

Hope this can help you in the design.

**Comment by jeanbisutti** [comment]
Interesting tool! Thank you @jlerbsc!

If you can find the time, I would be interested in having an analysis of [the core module](https://github.com/quick-perf/quickperf/tree/master/core).

**Comment by jlerbsc** [comment]
The 3d view of the core module is here http://jperf.com/qperf/core.html

You can zoom in/out in the view with the mouse and wheel, revolve around the graph with left mouse click and center the view with right mouse click.

Use filter to simply the view and problems to see coupling...

**Comment by jeanbisutti** [comment]
Interesting! Thank you @jlerbsc! I noted the links.

**Comment by jlerbsc** [comment]
Il n'y a pas de quoi... C'est ma petite contribution à ce projet ;-)
