### ISSUE TITLE
TestNG tests are not reliable

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#109]
**Describe the bug**
TestNG tests are not reliable.

I have one failure when running the test suite locally on Java 11, relaunching the test suite make the test pass

```
[ERROR] Failures: 
[ERROR]   AllocationAnnotationsTestNGTest.test_should_fail_if_test_method_annotated_with_no_allocation_allocates:54 
Expecting:
 <"a performance property is not respected

[PERF] Expected no heap allocation (test method thread) but is 728 bytes.
">
to contain:
 <"Expected no heap allocation (test method thread) but is 440 bytes."> 
```

I saw one failure in the CI on Java 8: https://travis-ci.com/github/quick-perf/quickperf/jobs/381900662

**Comment by jeanbisutti** [comment]
Thanks. I don't think it happens often.

**Comment by loicmathieu** [comment]
Two times in the same day ...
I really think you should keep this one open to trace these issues at least.
