### ISSUE TITLE
Unable to disable QuickPerf on a test method

### ISSUE THREAD

**Issue by gmarziou** [quick-perf/quickperf#131]
Hello,

Using QuickPerf 1.0, JUnit 5, Spring Boot 2.3.

I have a repository test class that is annotated with `@QuickPerfTest` but it contains few `@ParameterizedTest` annotated methods that are not supported so I tried to disable them by annotating them with `@DisableQuickPerf` but it does not work: they are still in error

```java
@SpringBootTest(classes = ServeurIsoleApp.class, webEnvironment = NONE)
@Import(QuickPerfSqlConfig.class)
@QuickPerfTest
class TapRepositoryIT {

    @ParameterizedTest
    @EnumSource(EtatTap.class)
    @DisableQuickPerf
    void enregistrement_avec_tous_les_etats(EtatTap etat) {
 ```

**Comment by jeanbisutti** [comment]
`@ParameterizedTest` uses JUnit 5 test template ([JUnit 5 code](https://github.com/junit-team/junit5/blob/main/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java#L123)). QuickPerf 1.0.0.  does not support JUnit 5 test template. There is the #114 PR to support it. :) I am going to review it. After the merging of this PR, I could deploy a snapshot version of QuickPerf. I could then propose you to check that everything is fine now in your tests with the snapshot version.

**Comment by gmarziou** [comment]
Thanks @jeanbisutti this would be great but you don't need to deploy a snapshot version, I can build it locally and test it.

**Comment by jeanbisutti** [comment]
Hello @gmarziou, for information, I reviewed  #114 PR

**Comment by jeanbisutti** [comment]
Hello  @gmarziou,  #114 was merged.

If you have time,  it would be nice to check that everything is now fine in your tests with QuickPerf master.

**Comment by gmarziou** [comment]
It works fine! Thanks to both @jeanbisutti and @loicmathieu
