### ISSUE TITLE
Support org.junit.jupiter.params.ParameterizedTest

### ISSUE THREAD

**Issue by klu2** [quick-perf/quickperf#139]
**Describe the bug**

The usage of JUnit5's  `org.junit.jupiter.params.ParameterizedTest` leads to a `RuntimeException`.

**Expected behavior**
QuickPerf can handle parameterized tests, the annotations are applied to all test runs

**Actual behavior**
A RuntimeException is thrown.

**To Reproduce**

```
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.ValueSource
import org.quickperf.junit5.QuickPerfTest

@QuickPerfTest
class FooTest {

    @ParameterizedTest
    @ValueSource(strings = ["foo", "bar"])
    fun paramTest(param:String) {

    }
}
```

Leads to

```
Quickperf didn't support test template yet
java.lang.RuntimeException: Quickperf didn't support test template yet
	at org.quickperf.junit5.QuickPerfTestExtension.interceptTestTemplateMethod(QuickPerfTestExtension.java:87)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)

```

**Versions**
- QuickPerf: 1.0.0
- JDK: 11
- OS: Windows

**Additional context** (Add any other context about the problem here.)

**Comment by jeanbisutti** [comment]
@klu2 Thanks for using QuickPerf. Could you please bump to QuickPerf 1.0.1? QuickPerf 1.0.1 should work with parameterized tests.

**Comment by klu2** [comment]
oh, 1.0.1 is already there, I didn't see that.
just gave it a try, works like a charm. 
thanks for this awesame framework!
