### ISSUE TITLE
@AnalyzeSql

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#141]
This feature aims to create an AnalyzeSql annotation that will analyze the SQL generated by a test.

The annotation will produce a report containing information such as:
* JDBC execution numbers
* SELECT number
* INSERT number
* DELETE number
* UPDATE number
* The potential presence of an N+1 select
* Checks performed by [the recommended SQL global annotations](https://github.com/quick-perf/doc/wiki/SQL-annotations#configure-global-annotations)

By default, the annotation will display the report on the console. The user will have the ability to export it elsewhere.

**Comment by FTarfasse** [comment]
Hi Jean,

I'd be happy to work on this !

**Comment by jeanbisutti** [comment]
Fixed with 707971ad04a780e797c04cffa5aeb1a10e41736e
