### ISSUE TITLE
QuickPerf should have a minimum version of Java 8

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#15]
**Description**
Today, the Maven Enforce plugin configuration of QuickPerf is configure for Java 7 compatiility !
Java 7 is EOL since April 2015 and a lot of libraries are compatible with Java 8 only.

**Implementation ideas**
Upgrade the Maven Enforce plugin configuration to target Java 8.

**Comment by jeanbisutti** [comment]
Hi @loicmathieu,

Thank you for your interest in QuickPerf!

The QuickPerf modules are configured for Java 7 compatibility,  except for one which has a Java 8 compatibility (https://github.com/quick-perf/quickperf/blob/master/spring/junit4-spring5/pom.xml). The idea is to be able to investigate performances on a legacy JDK 7 application.

A QuickPerf JUnit 5 module would a Java 8 compatibilty.

If a module having today a Java 7 compatibility would need a Java 8 library, you could discuss about this.

**Comment by loicmathieu** [comment]
I'm not agree, you will spend time working on keeping compatibility to not used anymore version instead of something else ... 
But it's your call

**Comment by jeanbisutti** [comment]
Until now, having a JDK 7 compatibility was not very time consuming.  If having a JDK 7 compatibility becomes a burden, we could change our position. You can notice that the core of Java Mission Control also maintains a JDK 7 compatibility.  Have the ability to investigate the performance properties of a legacy Java 7 applications seems to us an interesting feature.
