### ISSUE TITLE
GC declaration issue

### ISSUE THREAD

**Issue by FranckDemeyer** [quick-perf/quickperf#159]
**Describe the bug**
Hi, 
I think there's a little mistake made in GC enum class :
When declaring SHENANDOAH the flag used in JvmOption is set to`new JvmOption("-XX:+UseZGC")`

**Expected behavior**
I think the flag should be set to `new JvmOption("-XX:+UseShenandoahGC")`

Look directly at :
quickperf/jvm/jvm-annotations/src/main/java/org/quickperf/jvm/gc/GC.java

**Versions**
- QuickPerf: 1.0.1

**Comment by jeanbisutti** [comment]
Hi @FranckDemeyer,

Indeed, there is a mistake!

Thank you very much for taking the time to look at the QuickPerf code and noticing the mistake!

Would you be interested in providing a fix?

**Comment by FranckDemeyer** [comment]
Hi @jeanbisutti,
I'll send a PR as soon as I can.
😊

**Comment by jeanbisutti** [comment]
`I'll send a PR as soon as I can.
😊`

Great @FranckDemeyer! When you could!

**Comment by FranckDemeyer** [comment]
@jeanbisutti :
https://github.com/quick-perf/quickperf/pull/161

**Comment by jeanbisutti** [comment]
Fixed with 59dee49c1082d918e28c0312b80fd92eb6b01bd4. Thank you @FranckDemeyer!
