### ISSUE TITLE
Add bytes to allocation display

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#16]
Some annotations, like [@MeasureHeapAllocation](https://github.com/quick-perf/doc/wiki/JVM-annotations#MeasureHeapAllocation), can display allocation in console. The allocation is formatted with the help of `ByteAllocationMeasureFormatter` class.

For example:
```
Measured heap allocation: 3.1 Giga bytes
```

Now, we want that the formatted allocation also displays the allocation in bytes between parentheses if the allocation has a magnitude of kilo bytes, mega bytes or giga bytes.

For example:
```
3.9 Kilo bytes (4 056 bytes)
```

The test class to update is `ByteAllocationMeasureFormatterTest`.

If you start to work on this issue, please leave a comment "*I start to work on this issue*", so we can assign it to you.

**Comment by waterfl0w** [comment]
I am going to work on this.

**Comment by jeanbisutti** [comment]
Great @waterfl0w! Yes, we want the suffix if allocation is greater than or equal to 1KB. Don't hesitate if you need more information.

**Comment by jeanbisutti** [comment]
Thanks a lot for your work!
We would like to display allocation in bytes in a slightly different way, easier to read.
For example, for an allocation value of 100.0 Mega bytes, the expected display is 
```
100.0 Mega bytes (104 857 600‬ bytes)
```
and not 
```
100.0 Mega bytes (1.048576E8 bytes)
```
Could you please update the code to have the expected display?

**Comment by waterfl0w** [comment]
Sure. - Thank you for the feedback.
`NumberFormat#getIntegerInstance` does accept an optional `Locale`, otherwise it will automatically use a default value. Should I specifiy that it uses `Locale.ENGLISH` to ensure that it produces consistent formatting across all environments, or is default fine?

**Comment by jeanbisutti** [comment]
I am not sure that the expected display is going to depend on the Locale. If it was the case, the use of the English locale seems indeed better. To have the thousands separator defined with a blank, you may use the following piece of code together with a DecimalFormat:
```java
DecimalFormatSymbols symbols = DecimalFormatSymbols.getInstance();
symbols.setGroupingSeparator(' ');
```
More details here:  https://stackoverflow.com/questions/5323502/how-to-set-thousands-separator-in-java.
Thanks for your work. Don't hesitate if I can help.

**Comment by loicmathieu** [comment]
Maybe it should also be prefixed with `[QUICK PERF] ` in order to easily  see all logs related to QuickPerf in a glance.

**Comment by waterfl0w** [comment]
@jeanbisutti Thanks for guiding me through this. :) - I have adjusted the formatting now to reflect the initial intentions. 83a76b2

**Comment by jeanbisutti** [comment]
@loicmathieu I think it would be a good idea to add the prefix. I would rather to do this in another development.

**Comment by jeanbisutti** [comment]
@waterfl0w Huge thanks for the time you have spent working on this issue

**Comment by jeanbisutti** [comment]
@waterfl0w I will add you as contributor in Readme and pom this evening
