### ISSUE TITLE
[JUnit 5] Add an automatic test checking that global annotations work

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#26]
An annotation having a global scope applies on each test. More details [here](https://github.com/quick-perf/doc/wiki/QuickPerf#annotations-scope).

It is implemented with JUnit 4. The development of QuickPerf-JUnit 5 has begun.

Global annotations work with JUnit 5. The aim or this issue is to add an automatic test in [junit5-sql-test module](
https://github.com/quick-perf/quickperf/tree/master/junit5-sql-test) 

You can find an example of JUnit 5 SQL test [here](https://github.com/quick-perf/quickperf/blob/master/junit5-sql-test/src/test/java/org/quickperf/sql/QuickPerfJUnit5SqlTest.java).

Below the code (junit4-sql-test module) allowing to check that global annotations work with JUnit 4 :

https://github.com/quick-perf/quickperf/blob/master/junit4-sql-test/src/test/java/org/quickperf/sql/join/GlobalAnnotationTest.java

https://github.com/quick-perf/quickperf/blob/master/junit4-sql-test/src/test/java/org/quickperf/QuickPerfConfiguration.java

_We can help you to work on this issue. Don't hesitate to ask questions._

**Comment by gaurav9822** [comment]
@jeanbisutti Want to take this issue. Can you help?

**Comment by jeanbisutti** [comment]
Great @gaurav9822! I added details in the description. Don't hesitate if you need more information.
