### ISSUE TITLE
Add Oracle JDK 10 on CI (Travis)

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#27]
The aim of this issue is to add a build on Travis with Oracle JDK 10 and Linux.

**Comment by UtnansN** [comment]
I'd like to attempt this issue

**Comment by UtnansN** [comment]
Hmm, it seems like Travis has dropped support for oraclejdk10 and is failing builds immediately if oraclejdk10 is selected.  Should oraclejdk10 be downloaded from somewhere else for this?

Link - https://changelog.travis-ci.com/stop-a-job-early-if-a-deprecated-jdk-is-configured-76612

**Comment by jeanbisutti** [comment]
@UtnansN I did not know... Sorry about that. I think that the build would fail with OpenJDK JDK 10 because JFR profiling may not be compatible with this JDK. You may try and submit a PR if the build works with OpenJDK JDK 10. Thanks to have a look at this issue @UtnansN!

**Comment by jeanbisutti** [comment]
@UtnansN JFR was open source from JDK 11: https://dzone.com/articles/using-java-flight-recorder-with-openjdk-11-1
