### ISSUE TITLE
Have the ability to test SQL annotations on several databases with Testcontainers

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#33]
Today,  [automatic tests using a memory database (H2)](https://github.com/quick-perf/quickperf/tree/master/junit4-sql-test/src/test/java/org/quickperf/sql) verify that SQL annotations are working as expected.

With the help of [Testcontainers](https://www.testcontainers.org/), the goal of this issue is to can automatically verify that SQL annotations are working as expected on several non-memory databases (_Oracle_, _PostgreSQL_, ...).

*Don't hesitate to leave a comment if you have a question.*

**Comment by navkumar258** [comment]
Hi, looking for my first contribution. Please provide more details, a link/doc would suffice, about what needs to be done. thanks :smile:

**Comment by jeanbisutti** [comment]
@navkumar258  
A `sql-testcontainers-test` Maven module has to be added into [quickperf\sql](https://github.com/quick-perf/quickperf/tree/master/sql). A first step would be to execute [one of the tests using a memory database](https://github.com/quick-perf/quickperf/tree/master/sql/sql-integration-test/src/test/java) with a PostgreSQL database.
It's rather challenging for a first contribution!
@kanedafromparis has made impressive progress in [writing QuickPerf examples with TestContainers](https://github.com/quick-perf/quickperf-examples/pull/10). I prefer to wait for the end of @kanedafromparis work before starting this issue.

**Comment by jeanbisutti** [comment]
Fixed with a68fa6abfec5ae32a55f5812a74b4d34d2981db2
