### ISSUE TITLE
Micronaut & SQL annotations & JUnit 5

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#34]
SQL annotations can be used with JUnit 5.

We have to:
* use  `@QuickPerfTest`
* build a QuickPerf proxy of `javax.sql.DataSource`
```java
QuickPerfSqlDataSourceBuilder.aDataSourceBuilder().buildProxy(dataSource)
```
Given the JUnit 5 extension mechanism, SQL annotations should work with Micronaut + JUnit 5.

The aim of this issue is to check this and give an example using together @QuickPerfTest and [@MicronautTest](https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html#junit5). Don't forget to build a QuickPerf proxy of `javax.sql.DataSource` (see above).

The Micronaut example could be  given by creating Github project or by adding a non regression test in QuickPerf code (for example by adding a junit5-micronaut-sql-test Maven module).

*Don't hesitate to leave a comment if you have a question.*

**Comment by loicmathieu** [comment]
@jeanbisutti I can give some help here, what did you expect as the outcome of this issue ? Documentation ? Integration test inside the repository ?

It would be good to have the "same" sample application implemented with multiple frameworks (Spring, Micronaut, Quarkus) with the same set of tests.

**Comment by jeanbisutti** [comment]
The most usefull for users would certainly be a sample application, as you suggest. Wiki documentation and integration test inside the QuickPerf repository could come after. A Spring application is tested with [QuickPerf+JUnit4](https://github.com/quick-perf/springboot-junit4-examples) and [QuickPerf+Junit5](https://github.com/quick-perf/springboot-junit5-examples). It would be great to have the same thing for Micronaut and Quarkus.

**Comment by loicmathieu** [comment]
Great, I will try to port the sample Spring application to Micronaut and Quarkus.

**Comment by jeanbisutti** [comment]
Great @loicmathieu!
