### ISSUE TITLE
@DebugQuickPerf should display the QuickPerf JVM options

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#35]
**Description**
QuickPerf add some JVM options when you use some of it's features (for example JMC or some JVM related annotations).
These options should be displayed when the annotation `@DebugQuickPerf` is added to the test.

**Implementation ideas**
`ConsoleReporter.displayQuickPerfDebugInfos()` should logs the jvm options that QuickPerf add to the forked JVM.

**Comment by Minh-Trieu** [comment]
Working on it.

**Comment by jeanbisutti** [comment]
Closed by #51
