### ISSUE TITLE
Cannot resolve dependency org.openjdk.jmc:flightrecorder.rules.jdk:7.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by tvirtualw** [quick-perf/quickperf#36]
I have created a Spring Boot 2.2.1 project from https://start.spring.io/ and added `testImplementation 'org.quickperf:quick-perf-junit4-spring5:1.0.0-RC4'` as Gradle dependency.

Gradle cannot resolve org.openjdk.jmc:flightrecorder.rules.jdk:7.0.0-SNAPSHOT which seems to be required by org.quickperf:quick-perf-jvm-annotations:1.0.0-RC4.

The project uses OpenJDK11.

What am I missing?

**Comment by jeanbisutti** [comment]
QuickPerf uses one snapshot dependency, the one that Gradle cannot resolve. On Sonatype repository, only a snapshot version is available for this dependency. I have just discovered that a non snaphot version is available on AdoptOpenJDK / JFrog repository (since last septembre).
So, tomorrow I will test QuickPerf with the non snaphot version. If it seems OK, I will publish a new version of QuickPerf that should solve your issue.

**Comment by jeanbisutti** [comment]
I published a new version: 1.0.0-RC5
Could you please check with this one ?

**Comment by tvirtualw** [comment]
It works when I add `https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc-libs` as a repository to my Gradle project. Looks like the Maven pom.xml in the quickperf library sets this necessary repository by itself. I haven't tried using a Maven project - but I guess it works out of the box without adding that repository manually. I'm good for now, thanks for your help.

**Comment by jeanbisutti** [comment]
Thanks for this feedback! Could you please share the required Gradle configuration (the way to add https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc-libs as a repository to the Gradle project)? I could add it to the documentation to help other Gradle users. It seems to work with Maven. If you have questions on QuickPerf, don't hesitate.

**Comment by tvirtualw** [comment]
The `build.gradle` file contains a repositories section to which I have added the repository so it ends up looking like this:

```
repositories {
	mavenCentral()
	maven { url 'https://adoptopenjdk.jfrog.io/adoptopenjdk/jmc-libs' }
} 
```

**Comment by jeanbisutti** [comment]
Thanks a lot for this information!
