### ISSUE TITLE
Add @ExpectMaxQueryExecutionTime

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#4]
Provide an annotation to check the execution time of SQL queries.

**Comment by dialaya** [comment]
start work on it

**Comment by myluco** [comment]
How is this work going? Is there a way to help (part of Hackoctoberfest)

**Comment by jeanbisutti** [comment]
@myluco I would prefer not  to include this work in Hackoctoberfest. Thanks for your help proposal! :) In addition to #19, I could add more Hackoctoberfest issues in next days.

**Comment by rdm100** [comment]
Hi,

Is there more of a description of the issue?

**Comment by jeanbisutti** [comment]
@dialaya Are you always interested in working on this issue?

**Comment by jeanbisutti** [comment]
Closed by #53
