### ISSUE TITLE
Quarkus & SQL annotations & JUnit5

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#40]
**Description**
Provides integration tests for Quarkus, SQL annotations and JUnit5

**Implementation ideas**
Implements the same integration test than for Spring Boot, SQL annotations and JUnit4

**Comment by loicmathieu** [comment]
@jeanbisutti can you assign it to me?

**Comment by jeanbisutti** [comment]
An implementation is proposed [here](https://github.com/quick-perf/quickperf-examples/pull/6).

**Comment by loicmathieu** [comment]
The example has been implemented and merged inside the quickperf-example repository.
