### ISSUE TITLE
SpringBoot & SQL annotations & JUnit5

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#41]
**Description**
Provides integration tests for Spring Boot, SQL annotations and JUnit5

**Implementation ideas**
Implements the same integration test than for Spring Boot, SQL annotations and JUnit4

**Comment by loicmathieu** [comment]
@jeanbisutti can you assign it to me ?

**Comment by jeanbisutti** [comment]
I would not prefer to add integration tests with Spring Boot, SQL annotations and JUnit 5. Indeed, SQL annotations basically work thanks to the JUnit 5 extension mechanism. These tests would take several seconds to execute with Spring Boot and so would significantely increase the build length.
