### ISSUE TITLE
Add @ExpectMaxHeap

### ISSUE THREAD

**Issue by loicmathieu** [quick-perf/quickperf#42]
**Description**
We can define the heap of the forked VM but not make any assert of the value of it.

**Implementation ideas**
Add the annotation and the corresponding perf verifier

**Comment by jeanbisutti** [comment]
@HeapSize or @Xmx allowes to set the Xmx JVM option. So, some performance properties (heap allocation for example) can be evaluated in a JVM having this Xmx value.
Could you please explain the interest of checking the heap size with @ExpectMaxHeap (perhaps by giving a use case)?

**Comment by loicmathieu** [comment]
It's the same as the `@ExpectMaxRss` annotation but only on the memory part that is relative to the heap.
It assert that the test didn't use an heap that is more that what we expect.
It more targets integration test that launch the application than unit test that is better with the allocation related annotations.

**Comment by jeanbisutti** [comment]
Xms and Xmx are optional JVM options. If they are not provided, the JVM will use default values for them. These default values can vary from one machine to another. Xms and Xmx JVM options are most generally provided.
So, I would prefer not to include this annotation in QuickPerf. However, [you can create the annotation outside QuickPerf and use it in a project](https://github.com/quick-perf/doc/wiki/Create-an-annotation). If you demonstrate the utility of having this annotation providing a concrete use case then I will be happy to include it in QuickPerf.

**Comment by loicmathieu** [comment]
In fact this should have been named `@ExpectMaxUsedHeap` as `@ExpectMaxHeap` didn't means anything.
