### ISSUE TITLE
Add @ExpectUpdatedColumn

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#54]
**Description**
The aim of this annotation is to check the number of columns updated by a SQL UPDATE statement.

**Implementation steps**
The implementation steps are described ([here](https://github.com/quick-perf/doc/wiki/Create-an-annotation#steps-to-follow-to-add-a-sql-annotation-to-quickperf)).
[The code added to implement @ExpectUpdatedColumn will help you](https://github.com/quick-perf/quickperf/commit/eb81497e7db1ab49b9ed71032c7f4916feccf228).

If you start to work on this issue, please leave a comment "I start to work on this issue", so we can assign it to you. Do not hesitate to ask for information about the issue.

**Comment by balaaagi** [comment]
I would like to start working on this issue. Is it still open?

**Comment by jeanbisutti** [comment]
Hello @balaaagi 
Yes, you can work on this issue!

**Comment by jeanbisutti** [comment]
Hi @balaaagi,
Don't hesitate to tell me if I can help you!

**Comment by fabfas** [comment]
I start to work on this issue.

**Comment by jeanbisutti** [comment]
@fabfas: the issue is still open

@balaaagi: Do you have started working on this issue? Are you still interested or can we let @fabfas work on this issue?

**Comment by balaaagi** [comment]
@jeanbisutti I haven't made much progress on this. You can assign. Sorry for the inconvenience.

**Comment by jeanbisutti** [comment]
@balaaagi No problem, thanks for your feeback

@fabfas You can work on this issue, don't hesitate to tell me if I can help you

**Comment by jeanbisutti** [comment]
Closed by #59
