### ISSUE TITLE
Add Maven wrapper

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#6]
Tutorial: https://www.baeldung.com/maven-wrapper

If you start to work on this issue, please leave a comment "I start to work on this issue", so we can assign it to you.

**Comment by emcdow123** [comment]
Hey @jeanbisutti, I'd love to get started working on this!

**Comment by emcdow123** [comment]
I start to work on this issue

**Comment by emcdow123** [comment]
@jeanbisutti pull request created https://github.com/quick-perf/quickperf/pull/18

**Comment by jeanbisutti** [comment]
Thanks @emcdow123 for your work!
