### ISSUE TITLE
Make @ProfileJvm display the allocation rate

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#64]
**Description**

With @ProfileJvm annotation, the JVM is profiled with the [JDK Flight Recorder](https://en.wikipedia.org/wiki/JDK_Flight_Recorder), an event recorder built into the JVM.

With this annotation, some JVM data are displayed in the standard output.

Example:
```
 ALLOCATION (estimations)  |   GARBAGE COLLECTION           |  THROWABLE
 Total:        3,7 GiB     |   Total pause: 1,087 s         | Exception: 0
 Inside TLAB:  3,69 GiB    |   Longest GC pause: 160,438 ms | Error: 36
 Outside TLAB: 10,3 MiB    |                                | Throwable: 36
```
The aim of this issue is to add the allocation rate.

**Implementation ideas**
* Class displaying JVM data: `DisplayJvmProfilingValueVerifier`
* Total allocation can be computed by using `JdkAggregators.ALLOCATION_TOTAL`.
 ```java
    IQuantity totatlAlloc =(IQuantity) itemCollection.getAggregate(JdkAggregators.ALLOCATION_TOTAL);
    long allocationInBytes = totatlAlloc.longValue();
 ```
* The duration can be computed in the following way:
  *  Filter IItemCollection by inside and outside TLAB events: 
    ```java
       itemCollection.apply(JdkFilters.ALLOC_INSIDE_TLAB)       
       itemCollection.apply(JdkFilters.ALLOC_OUTSIDE_TLAB)
     ```

  * Retrieve the min and max timestamps
    Code to get the timestamp of a JFR event below
     ```java
     IType<IItem> type= (IType<IItem>) item.getType();
     IMemberAccessor<IQuantity, IItem> endTimeAccessor = JfrAttributes.END_TIME.getAccessor(type);
	IQuantity quantityEndTime = endTimeAccessor.getMember(jfrEvent);
	long timeStampInMs = quantityEndTime.longValueIn(UnitLookup.EPOCH_MS);
    ```
  * Compute the difference between the min and max time stamps
* Compute (total allocation)/duration

**Comment by edwardrose946** [comment]
Hi Jeanbisutti,

I'm looking for my first open source project to contribute to and would like to help. I am comfortable with Java, Maven and Git, but might need a little support as a first timer.

May I work on this issue? 

Kind regards, 

Edward Rose

**Comment by jeanbisutti** [comment]
@edwardrose946 

Hi Edward Rose,

Great, you are welcome!

I assign this issue to you.

I can help for your first contribution. Don't hesitate.

Kind regards

**Comment by edwardrose946** [comment]
Hi Jean, 

Thanks for the assignment. 

Quick questions: 

The two extra lines to add to the output will be allocation rate inside TLAB and allocation rate outside TLAB?

The calculation will return a long and won't have an associated JdkAggregator. I know I can just format the result as a String and put it in the table, but this isn't reusing the existing string formatting methods in ProfilingInfo. I feel like I am missing some understanding to best use the existing code and keep it clean, do you have any tips?  

Kind regards

**Comment by jeanbisutti** [comment]
Hi Edward,

> The two extra lines to add to the output will be allocation rate inside TLAB and allocation rate outside TLAB?

The extra line will be the total allocation rate (inside and outside TLAB).

Total allocation can be computed by using `JdkAggregators.ALLOCATION_TOTAL`.
 ```java
    IQuantity totatlAlloc =(IQuantity) itemCollection.getAggregate(JdkAggregators.ALLOCATION_TOTAL);
    long allocationInBytes = totatlAlloc.longValue();
 ```

> The calculation will return a long and won't have an associated JdkAggregator. I know I can just format the result as a String and put it in the table, but this isn't reusing the existing string formatting methods in ProfilingInfo. I feel like I am missing some understanding to best use the existing code and keep it clean, do you have any tips?

Something is missing in the issue description, sorry about that. 
From the long value, we can instanciate an Allocation object and format the allocation value with the `ByteAllocationMeasureFormatter`:
 ```java
Allocation allocation = new Allocation(allocationInBytes, AllocationUnit.BYTE); 
String allocationAsString = ByteAllocationMeasureFormatter.INSTANCE.format(measuredAllocation);
 ```
" /s" string has also to be added. Perhaps that the addition of an `AllocationRateMeasureFormatter  `could also manage this.

Kind regards

**Comment by edwardrose946** [comment]
Hi Jean,

Thank you for your guidance so far. 

![Capture](https://user-images.githubusercontent.com/61411652/82091219-e06f6100-96ee-11ea-8931-4198bda53180.PNG)

Sorry for the slow progress, this is turning into quite a humbling experience. I am making progress though. I have some further questions before I will commit:

```
itemCollection.apply(JdkFilters.ALLOC_INSIDE_TLAB)      
itemCollection.apply(JdkFilters.ALLOC_OUTSIDE_TLAB)
```
This is my first time using IItemCollections. I am currently accessing and iterating over the event time stamps in a very ugly way to find the min/max. What is the best way to access the `EventArray` from the `EventCollection` within the `IItemCollection` returned from the filter?

I will make an `AllocationRateMeasureFormatter` so the output can fit in the first column.

Lastly, if the difference between the max time stamp and minimum timestamp is zero milliseconds (say creating a single object) what would the appropriate output be for the allocation rate? (Empty String, Undefined or go to micro, nano seconds etc.)

**Comment by jeanbisutti** [comment]
Hi Edward,

Thanks a lot for your work! 

You are close to the end of this issue based on JDK Mission Control  API!

Regarding the iteration with IItemCollections, I would write the code in the following way:

```java
        IItemCollection allocInsideTlabItemCollection = itemCollection.apply(JdkFilters.ALLOC_INSIDE_TLAB);

        for (IItemIterable items : allocInsideTlabItemCollection) {
            IType<IItem> type = items.getType();
            IMemberAccessor<IQuantity, IItem> endTimeAccessor = JfrAttributes.END_TIME.getAccessor(type);
            for (IItem item : items) {
                IQuantity quantityEndTime = endTimeAccessor.getMember(item);
                long timeStampInMs = quantityEndTime.longValueIn(UnitLookup.EPOCH_MS);
            }
        }
```
Perhaps there would be a better way to do this.

The first column can be broadened with the help of `StringWidthAdapter`.

If the difference between the max time stamp and minimum timestamp is zero millisecond, I would display an empty String.

It would be great if the allocation rate was displayed by second.

Don't hesitate if I can help you.

**Comment by edwardrose946** [comment]
Hi Jean,

In my allocation rate class I started with one public method, then broke it down into several private methods for readability. Before this project I hadn't used Mockito and with JUnit/Mockito I can't test private methods.

I read this <a href="https://www.artima.com/suiterunner/private.html">blog post</a> and decided to just test the public method. I have used Mockito to mock `IItemCollection jfrEvents` for testing my calculation methods and I ended up having to mock lots of objects, making the realisation that this wasn't the way to use it.... 

Would you recommend any further testing approaches?

Still I believe my methods work, deal with edge cases and have been tested. I have pushed to my fork.

Thank you kindly for your support so far.

KRs

Edward

**Comment by jeanbisutti** [comment]
Hi Edward,

Thanks a lot for your great work.

I am a [PR in your repo](https://github.com/edwardrose946/quickperf/pull/1) containing some improvements.

Could you please merge this PR, squash the commits and after that create a PR for the QuickPerf repository?

I hope that this issue was not too difficult for a first contribution.

You are welcome if you would like to continue to contribute to QuickPerf.

Kind regards,

Jean

**Comment by edwardrose946** [comment]
Hi Jean,

Thank you so much for your time and patience. I believe I have properly squashed the commits and created a PR. I will carefully look through your edits as I have a lot to learn from them. I hope I can continue to contribute.

Yours kindly,

Edward Rose

**Comment by jeanbisutti** [comment]
Hi Edward,

Thank you so much for your great work.

You are very welcome to continue to contribute.

Kind regards,

Jean Bisutti
