### ISSUE TITLE
Create a QuickPerf web site

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#7]
The website will contain the documentation, the release notes, ...

**Comment by navkumar258** [comment]
@jeanbisutti i can start working on this, please share some ides about how to start...scope,pages,layout,etc. thanks !

**Comment by jeanbisutti** [comment]
@navkumar258 I will detail what is expected

**Comment by jeanbisutti** [comment]
@navkumar258 

The web site will use on Jekyll with a [Minimal mistakes style](https://mmistakes.github.io/minimal-mistakes/).

@loicmathieu started a prototype:
* https://github.com/loicmathieu/quickperf.io
* https://loicmathieu.github.io/quickperf.io/

You could continue from this.

In the header, it would be nice to add:
* A Twitter logo pointing to https://twitter.com/quickperf
* A YouTube logo pointing to https://www.youtube.com/playlist?list=PLyRtZQwOxA6ekhEr2H2nNV42ZLD8OkPEx

`quickperf.io` has to be replaced by `org.quickperf`

It would be great to have a black background by default and perhaps to be able to switch to a white background:
![image](https://user-images.githubusercontent.com/14811066/89437933-78a64080-d748-11ea-888b-2e41fb14fbd4.png)
https://mademistakes.com/work/minimal-mistakes-jekyll-theme/
https://github.com/mmistakes
I could supply a QuickPerf logo with a black background.

It would be nice to move the documentation (https://github.com/quick-perf/doc/wiki/QuickPerf) to the website. You can clone the current documentation from https://github.com/quick-perf/doc.wiki

**Comment by navkumar258** [comment]
@jeanbisutti seems like a lot of work to do.... :smiley: .Will start working once familiar with the above docs. Hope there are no stringent timelines...?!

**Comment by jeanbisutti** [comment]
No problem @navkumar258, progress at your own pace

**Comment by jeanbisutti** [comment]
Hi @navkumar258,

Did you have the possibility to work  on this issue?

**Comment by navkumar258** [comment]
Heyy @jeanbisutti : No haven't progressed yet. Actually, I moved to a different role. If you want, assign it to someone else.

**Comment by jeanbisutti** [comment]
@navkumar258 No problem You are welcome if you want to work on QuickPerf

**Comment by guiRagh** [comment]
I am currently working on the jekyll website.
I added the social links in the header, I am waiting for Loic's news to have access to his repo to create Pull Request.

I am now looking at how to offer the option to change the theme from white to black.

**Comment by jeanbisutti** [comment]
> @jeanbisutti can you supply logo for black theme ? background with color #252a34 .
We need the logo with just the lightning bolt, and the image with the lightning bolt and quickperf.

@guiRagh Images are available [here](https://github.com/jeanbisutti/logo) 
Don't hesitate to tell me if you need other things

**Comment by guiRagh** [comment]
This issue should be closed, the specifications are all met. 
@jeanbisutti Can you explain what you want to put in the different sections of the site? can be here or on another issue (preference for an issue on @loicmathieu repo).

**Comment by jeanbisutti** [comment]
@guiRagh Thank you very much! 👍 

I noticed that you don't use the `quickperf - 252a34 background.svg` and `lightning bolt - 252a34 background.svg` images. Would it be possible to use them with the dark theme and enable the dark theme by default?

After that, would it be possible to merge all your branches  into your `gh-pages` branch? I could then make a PR with a few text modifications,  I could fork your repo with  the QuickPerf Github account, and we could continue with the QuickPerf repo.

The following steps would be to migrate the documentation (probably a lot of work).

Once again, thank you very much @guiRagh!

**Comment by loicmathieu** [comment]
@jeanbisutti I can help to migrate the documentation, don't hesistate to ping me if needed.

**Comment by jeanbisutti** [comment]
> @jeanbisutti I can help to migrate the documentation, don't hesistate to ping me if needed.

Thank you @loicmathieu!

**Comment by guiRagh** [comment]
> @guiRagh Thank you very much! 👍
> 
> I noticed that you don't use the `quickperf - 252a34 background.svg` and `lightning bolt - 252a34 background.svg` images. Would it be possible to use them with the dark theme and enable the dark theme by default?
> 
> After that, would it be possible to merge all your branches into your `gh-pages` branch? I could then make a PR with a few text modifications, I could fork your repo with the QuickPerf Github account, and we could continue with the QuickPerf repo.
> 
> The following steps would be to migrate the documentation (probably a lot of work).
> 
> Once again, thank you very much @guiRagh!

All is done !
[https://guiragh.github.io/quickperf.io/](Preview available)

**Comment by jeanbisutti** [comment]
Many thanks @guiRagh!

I forked the website repo with the QuickPerf Github account: https://github.com/quick-perf/quickperf.io 

You may be interested in [other website issues](https://github.com/quick-perf/quickperf/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite).

Once again, many thanks for your work @guiRagh!
