### ISSUE TITLE
Make @ProfileJvm display the old GC count

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#70]
**Description**

With @ProfileJvm annotation, the JVM is profiled with the [JDK Flight Recorder](https://en.wikipedia.org/wiki/JDK_Flight_Recorder), an event recorder built into the JVM.

With this annotation, some profiling data are displayed in the standard output.

For example:
```
 ALLOCATION (estimations)  |   GARBAGE COLLECTION           |  THROWABLE
 Total:        3,7 GiB     |   Total pause: 1,087 s         | Exception: 0
 Inside TLAB:  3,69 GiB    |   Longest GC pause: 160,438 ms | Error: 36
 Outside TLAB: 10,3 MiB    |                                | Throwable: 36
```

The aim of this issue is to also display the number of old collections.

With two old collections, we expect to display _Old: 2_ below _Longest GC pause_.

**Implementation**

* Class displaying the profiling data: DisplayJvmProfilingValueVerifier

* To get the number of old collections:
```java
        IItemFilter oldGC = ItemFilters.type("jdk.OldGarbageCollection");
        ItemsAndItemsForDifferenceCollection oldGcItemCollection = jfrEvents.apply(oldGC);

        int oldGcCount = 0;
        for (IItemIterable items : oldGcItemCollection) {
            oldGcCount += items.getItemCount();
        }
```

If you start to work on this issue, please leave a comment _I start to work on this issue_, so we can assign it to you. Do not hesitate to ask for information about the issue.

**Comment by UbaidurRehman1** [comment]
I would like to work on it.

**Comment by jeanbisutti** [comment]
Thanks @UbaidurRehman1! I suggest to assign this issue to you after your work on #71.

**Comment by UbaidurRehman1** [comment]
One more thing for clarification: Should I extend my local branch for #71 or create new branch from master?

**Comment by jeanbisutti** [comment]
@UbaidurRehman1 I recommend to add the new code to your local branch and push it. The new code will be added to #76 PR. I think it is the more simple thing to do.

**Comment by UbaidurRehman1** [comment]
Pull request created. #79

**Comment by jeanbisutti** [comment]
Thanks a lot for your contribution @UbaidurRehman1!
