### ISSUE TITLE
Make @ProfileJvm display the young GC count 

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#71]
With @ProfileJvm annotation, the JVM is profiled with the [JDK Flight Recorder](https://en.wikipedia.org/wiki/JDK_Flight_Recorder), an event recorder built into the JVM.

With this annotation, some profiling data are displayed in the standard output.

For example:
```
 ALLOCATION (estimations)  |   GARBAGE COLLECTION           |  THROWABLE
 Total:        3,7 GiB     |   Total pause: 1,087 s         | Exception: 0
 Inside TLAB:  3,69 GiB    |   Longest GC pause: 160,438 ms | Error: 36
 Outside TLAB: 10,3 MiB    |                                | Throwable: 36
```

The aim of this issue is to also display the number of young collections.

With two young collections, we expect to display _Young: 2_ below _Longest GC pause_..

**Implementation**

* Class displaying the profiling data: DisplayJvmProfilingValueVerifier

* To get the number of young collections:
```java
      IItemFilter youngGC = ItemFilters.type("jdk.YoungGarbageCollection");
        ItemsAndItemsForDifferenceCollection youngGcItemCollection = jfrEvents.apply(youngGC);

        int youngGcCount = 0;
        for (IItemIterable items : youngGcItemCollection) {
            youngGcCount += items.getItemCount();
        }
```

If you start to work on this issue, please leave a comment _I start to work on this issue_, so we can assign it to you. Do not hesitate to ask for information about the issue.

**Comment by UbaidurRehman1** [comment]
I would like to work on it.

**Comment by jeanbisutti** [comment]
Great @UbaidurRehman1! I assign this issue to you. Don't hesitate if you need help.

**Comment by UbaidurRehman1** [comment]
I have written the code but my question is: 
How to display the profiling data? Is there any tests?  I have checked all JMC tests but no one display the profiling data? (as above)

**Comment by jeanbisutti** [comment]
@UbaidurRehman1 I am sorry, I did not see your message...
To display the profiling data, in `JmcJUnit4Tests` class you can replace  `@ExpectNoJvmIssue(score = 50)` by `@ProfileJvm`. You may have to reduce heap size (` @HeapSize(value = 100, unit = AllocationUnit.MEGA_BYTE)`) in order to get young garbage collections.
It is possible to mock the JFR events, [an example](https://github.com/edwardrose946/quickperf/blob/EdwardRose946/jvm/jvm-annotations/src/test/java/org/quickperf/jvm/jmc/value/AllocationRateTest.java).
Automatic tests are not mandatory in the frame of this issue (we may consider that mocking JFR events leads to test the implementation details). Regarding the automatic tests, as you wish...

**Comment by UbaidurRehman1** [comment]
Pull request created.

**Comment by jeanbisutti** [comment]
Fiixed with #76
