### ISSUE TITLE
Add Javadoc to core annotations

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#88]
_core annotations_ are documented in QuickPerf [wiki](https://github.com/quick-perf/doc/wiki/core-annotations) .

The goal of this issue is to add Javadoc to _core annotations_ that are located in [core Maven module](https://github.com/quick-perf/quickperf/tree/master/core/src/main/java/org/quickperf/annotation).

The documention contained in QuickPerf wiki can be used to add Javadoc to the _core annotations_. Don't hesitate to improve it.

**Comment by FTarfasse** [comment]
Hi Jean,

I would like to work on this please.

Question: can you precise me the difference between @[FunctionalIteration](https://github.com/quick-perf/quickperf/blob/b3f71aba6a43e09dd589bd97a7e955acc628f143/core/src/main/java/org/quickperf/annotation/FunctionalIteration.java#L21) and @[DisableQuickPerf](https://github.com/quick-perf/quickperf/blob/b3f71aba6a43e09dd589bd97a7e955acc628f143/core/src/main/java/org/quickperf/annotation/DisableQuickPerf.java#L21) please (except the fact we can add a comment on one of the two) ? The Runner classes seems to consider them equally (they both completely disable annotations) but I feel I am missing something ...

Thanks,

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Great! I assign this issue to you.

> Question: can you precise me the difference between @FunctionalIteration and @DisableQuickPerf please (except the fact we can add a comment on one of the two) ? The Runner classes seems to consider them equally (they both completely disable annotations) but I feel I am missing something ...

`@FunctionalIteration` and `@DisableQuickPerf ` have the same behavior. They disable QuickPerf.

During a feature implementation, `@FunctionalIteration`  is more explicit than `@DisableQuickPerf` about focusing on functional behavior (not performance behavior) in a first step. Without `@FunctionalIteration` or `@DisableQuickPerf`, the test may fail because of [global performance  annotation](https://github.com/quick-perf/doc/wiki/QuickPerf#annotation-scopes) even if the functional behavior is ok. In a second implementation step, you can remove @FunctionalIteration to evaluate some performance properties. 

We recommend to do one step at a time: we implement the functional behavior and after we focus on some performance characteristics.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hello Jean,

I re-submitted a PR with your feedbacks. I tweaked a bit your proposal for @FunctionalIteration.

Let me know your opinion !

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hello Fabrice,

That's great! Many thanks Fabrice!!!

Thank you a lot for all your contributions.

Kind regards,

Jean

**Comment by jeanbisutti** [comment]
Fixed with a3855ed6a292302fc3bc3de7db376565b414631c

**Comment by FTarfasse** [comment]
As always, happy to help !
