### ISSUE TITLE
Add Javadoc to JVM annotations

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#89]
_JVM annotations_ are documented in QuickPerf [wiki](https://github.com/quick-perf/doc/wiki/JVM-annotations).

The goal of this issue is to add Javadoc to _JVM annotations_ that are located in [jvm-annotations Maven module](https://github.com/quick-perf/quickperf/tree/master/jvm/jvm-annotations).

The documentation contained in QuickPerf wiki can be used to add Javadoc to the _JVM annotations_. Don't hesitate to improve it.

**Comment by VinitaNirmal** [comment]
Is the task that, we have to add the comments on top of the annotations??

**Comment by jeanbisutti** [comment]
Hello,

Javadoc has to be added in the JVM annotations in [the same way it is done for SQL annotations](https://github.com/quick-perf/quickperf/commit/ccaf9b083454762074bc11f6d9d4251b3203df53), with a package info.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hello Jean,

Is anyone working on this ? I can do it if it is not the case (to finish the topic for once and for all !).

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hello Fabrice,

Nobody is working on this issue. I assign it to you.

Many thanks for your contributions.

Don't hesitate if you have any questions.

Kind regards,

Jean

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Don't worry about the delay. I looked at your draft. It's great, many thanks! I made [a few suggestions](https://github.com/FTarfasse/quickperf/commit/9bd81c6587d5d03eaab14372d5f066aad32e7511). Don't hesitate if you have any questions, and don't hesitate to submit a PR!

 About, `@ProfileQuickPerfInTestJvm` there was a bug with JDK > 1.8. Thank you for the report. The aim if this annotation is to 
profile QuickPerf. It's not a public annotation; it is not needed to document it. The bug is now fixed on head.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hi Jean,

Thanks for your feedbacks !
I added a new [commit](https://github.com/FTarfasse/quickperf/commit/52718d17ef400e49ab0546126e8bc47d63e2b463) based on your suggestions as I wanted the corrections to be clear (I'll squash everything for the PR).

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Fixed with 9ab2d8e1b9c548a4f406eda2201632cf4fdabc4d.

Thank you @FTarfasse!
