### ISSUE TITLE
Add Javadoc to SQL annotations

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#90]
_SQL annotations_ are documented in QuickPerf [wiki](https://github.com/quick-perf/doc/wiki/SQL-annotations).

The goal of this issue is to add Javadoc to _SQL annotations_ that are located in [sql-annotations Maven module](https://github.com/quick-perf/quickperf/tree/master/sql/sql-annotations).

The documentation contained in QuickPerf wiki can be used to add Javadoc to the _SQL annotations_. Don't hesitate to improve it.

**Comment by FTarfasse** [comment]
Hello Jean,

I'd like to work on this issue. 
I'll try to show you a draft soon enough on a few annotations to make sure I am on the right track.

In addition to this I'll make a PR to update the wiki with the latest annotations from v1.

Let me know if it is ok for you.

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hello Fabrice,

It would be really great!

About the wiki, at first sight, it is not possible to make a PR... What perhaps could be done: you could fork the [wiki projet](https://github.com/quick-perf/doc), update it and I would report the modifications in the QuickPerf wiki.

Kind regards,

Jean

**Comment by FTarfasse** [comment]
![ExpectJdbcBatching_Javadoc](https://user-images.githubusercontent.com/41832786/86496947-d0cfd880-bd7f-11ea-8ece-7e1d84aedff7.png)

**Comment by FTarfasse** [comment]
Hello Jean,

So, after today's deep dive in the docs I need your opinion on these points please:
1. Below is a draft with the @ExpectJdbcBatching annotation javadoc I generated locally (I took as a reference JUnit4's way of "javadocumenting" things).
Is it ok for you ? I adapted the wiki infos .

2. As I was reading SQL annotations tests I noticed that [@DisableCrossJoin](https://github.com/quick-perf/quickperf/blob/master/sql/sql-annotations/src/main/java/org/quickperf/sql/annotation/DisableCrossJoin.java) was missing in the tests [directory](https://github.com/quick-perf/quickperf/tree/master/sql/sql-integration-test/src/test/java).
I found an equivalent test [here](https://github.com/quick-perf/quickperf/blob/master/junit4/junit4-sql-test/src/test/java/org/quickperf/sql/DisableAnnotationTest.java) (JUnit4 directory ?) but I am confused as there is only EnableCrossJoin annotation (I was expecting to find DisableCrossJoin annotation followed by the Enable one (as the enable deactivates the disable)). A clarification would be highly appreciated.
Anyway, should we do something with this DisableAnnotationTest file ? Move it with the other SQL annotations tests ? Remove it and create a @DisableCrossJoinTest (as usually only Disable annotations tests exist in the test directory) ? Should we create tests for Enable annotations ?
I am sorry if this seems overkill but I spent a long time comparing the wiki, the tests and the annotations source code. I'd be happy to continue updating what needs to be, tests included :).

Thanks for your feedbacks,

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hello Fabrice,

1. It's great!

   Some improvements:
   * "Batching  of inserts, updates and deletes statements allows" => ""Batching  of insert, update and deletesstatements allows". I fixed the wiki.
   * In Javadoc, replace some `*...*` by `<code>..</code>`
   * Add a line break before `Example:`
    

2.  `@DisableCrossJoin`  and `@DisableCrossJoin` should be removed (not in the scope of this issue). Indeed, cross join does not necessarily impact performance with modern databases, see for example: https://twitter.com/lukaseder/status/1207971510671073286
About `DisableAnnotationTest`, `@DisableCrossJoin` is configured with a global scope with [this configuration file]( https://github.com/quick-perf/quickperf/blob/master/junit4/junit4-sql-test/src/test/java/org/quickperf/QuickPerfConfigurationJUnit4.java). A annotation with a [global scope](https://github.com/quick-perf/doc/wiki/QuickPerf#annotation-scopes) applies on each test.
`@EnableCrossJoin` cancels the behavior of `@DisableCrossJoin` 
`@EnableCrossJoin`  and `@DisableCrossJoin` should be removed and `DisableAnnotationTest` has to be rewritten without these annotations  (not in the scope of this issue). `DisableAnnotationTest`  goal is to check that an annotation can disable another one:
```java
    SqlAnnotationsConfigs.java
    static final AnnotationConfig ENABLE_SQL_CROSS_JOIN = new AnnotationConfig.Builder()
            .cancelBehaviorOf(DisableCrossJoin.class)
            .build(EnableCrossJoin.class);
```
`DisableAnnotationTest` is not specific to SQL annotations. For convenience, the fact that an annotation can disable another one is tested with SQL annotations.

I am sorry if the code was confusing. Feedbacks are welcome.

Kind regards

Jean

**Comment by FTarfasse** [comment]
Hi Jean,

Thank you for your previous feedback, every time I think I got a good understanding on part of the code base something unexpected comes in the way :).

Concerning the issue, I pushed to my master branch all the Javadoc I added on the SQL annotations (I rebased before today). Do you prefer reviewing "there" or should I do a PR (I have no clue which is the easiest from your perspective) ?

Anyhow, I did my best (it definitly took some time) and it is a starting point so every feedback is welcome.

Thanks !

P.S. : I work in parallel on the corresponding wiki pages, I'll show you an update this week.

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Hi Fabrice,

I am sorry to reply a few days later.

Many thanks for your work. It's great!

I suggest some modifications [on your master branch](https://github.com/FTarfasse/quickperf/commit/943fda0e34d48fe6ae911ea274b72ca18b722661).

 Don't hesitate to do a PR in QuickPerf repo.

Kind regards,

Jean

**Comment by jeanbisutti** [comment]
Hi Fabrice,

Many thanks for you last code update!

[I suggest other modifications](https://github.com/FTarfasse/quickperf/commit/b4b4ad618bbcc7f092e00061c30f1df107f17e88).

What do you think?

Kind regards,

Jean

**Comment by FTarfasse** [comment]
Hi Jean,

Thanks for your feedbacks ! What I did was to:

- Replace "Cancel" by "Cancels" and "Optionnaly specifies" by "Specify"
- Correct links between enable and disable annotations
- Replace @ by their corresponding html entity in DisplaySql and remove Javadoc duplicate in DisplaySqlOfTestMethodBody (this why the number of added lines is lower in the latest commit).

New commit is [here](https://github.com/FTarfasse/quickperf/commit/199e1c623117c57c5370572dfc88d408e0b74541), previous with your feedbacks is [there](https://github.com/FTarfasse/quickperf/commit/b4b4ad618bbcc7f092e00061c30f1df107f17e88#commitcomment-40501965).

Kind regards,
Fabrice

**Comment by jeanbisutti** [comment]
Thank you Fabrice.

"Specify" should not be replaced with "Specifies"?

Kind regards,

Jean

**Comment by FTarfasse** [comment]
You are correct :), I fixed it (I also updated ExpectJdbcBatching the same way: Optionnaly specify => Specifies) !

**Comment by jeanbisutti** [comment]
Great! OK to create a PR?

**Comment by jeanbisutti** [comment]
Fixed with  ccaf9b083454762074bc11f6d9d4251b3203df53

**Comment by jeanbisutti** [comment]
Thank you Fabrice!

**Comment by FTarfasse** [comment]
My pleasure :) !
